spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    #eureka 实例主机名
    hostname: localhost
  client:
    #标识是否从Eureka Server 获取注册信息，默认是true。 如果这是一个单节点的Eureka Service
    #不需要同步其他节点的数据，设置为false
    fetch-registry: false
    #是否将自己注册到 Eureka Server,默认是true 由于当前应用是单节点的Eureka Server
    #需要设置为 false
    register-with-eureka: false
    #设置Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/